name: "Hello World Custom Action"
description: "Outputs a custom message"
inputs:
  message:
    description: "Message to print"
    required: false
    default: "Hello World"
outputs:
  script_result:
    description: "Output from script"
    value: ${{ steps.process_message.outputs.script_result }}
  echo_result:
    description: "Output from echo"
    value: ${{ steps.set-result.outputs.echo_result }}
runs:
  using: "composite"
  steps:
    - name: Process message
      id: process_message
      run: bash ${{ github.action_path }}/entrypoint.sh "${{ inputs.message }}"
      shell: bash
    - name: Return message
      id: set-result
      run: echo "echo_result=${{ inputs.message }} (hogehoge)" >> $GITHUB_OUTPUT
      shell: bash
      
    # - run: bash ${{ github.action_path }}/entrypoint.sh "${{ inputs.message }}"
    #   shell: bash
    # - name: Process message
    #   run: |
    #     echo "Received message: ${{ inputs.message }}"
    #     echo "result=${{ inputs.message }} (processed)" >> $GITHUB_ENV
    #   shell: bash
