name: "Hello World Custom Action"
description: "Outputs a custom message"

inputs:
  message:
    description: "Message to print"
    required: false
    default: "Hello World"
    
outputs:
  script_result:
    description: "Output from script"
    value: ${{ steps.process_message.outputs.script_result }}
  echo_result:
    description: "Output from echo"
    value: ${{ steps.set-result.outputs.echo_result }}
  csharp_result:
    description: 'The result from C# code'
    value: ${{ steps.csharp.outputs.csharp_result }}
    
runs:
  using: "composite"
  steps:
    - name: Process message
      id: process_message
      shell: bash
      run: bash ${{ github.action_path }}/entrypoint.sh "${{ inputs.message }}"

    - name: Return message
      id: set-result
      shell: bash
      run: 'echo "echo_result=Echo Processed: ${{ inputs.message }} (hogehoge)" >> $GITHUB_OUTPUT'
      #run: echo "echo_result=${{ inputs.message }} (hogehoge)" >> $GITHUB_OUTPUT
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Run csharp code
      id: csharp
      shell: bash
      run: dotnet run --project ${{ github.action_path }}/MyProject.csproj "${{ inputs.message }}"
